#!/usr/bin/env bash
# Bash script that transfers a file from a client to a server

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	PATH_TO_FILE=$1
	USER=$3
	IP=$2
	SSH_KEY=$4
	
	if [ -z "$SSH_KEY" ]; then
		scp -T "$PATH_TO_FILE" "$USER"@"$IP":~/
	else
		scp -T -i "$SSH_KEY" "$PATH_TO_FILE" "$USER"@"$IP":~/
	fi

fi

