#!/usr/bin/env bash
#	=== 	Install nginx web server	===
ssh ubuntu@54.87.204.116 "sudo apt-get -y update && sudo apt-get -y install nginx"

#	===		listen on port 80	===


ssh -t ubuntu@54.87.204.116 << 'EOF'
SITE_CONF="/etc/nginx/sites-available/default"
PORT=80
#get the lines with lines numbers that has the word 'listen'
grep -n 'listen' "$SITE_CONF" |
# execlude comments and lines has 'ssl' (https)
grep -v -E 'ssl|#' |
# Extracts the first field (before the colon) (only line numbers)
cut -d ':' -f1 | \
#Uses the extracted field as a pattern (__) to replace PORT for these lines with the value of the PORT variable
xargs -I __ sudo sed -i "__s/[0-9]\+/$PORT/" "$SITE_CONF"
EOF


# 	=== (requesting a page) using curl, returns a page that contains the string Hello World!	===

ssh ubuntu@54.87.204.116 << 'EOF'
INDEX_DIR="/var/www/html"
echo "Hello World!" | sudo tee "$(find "$INDEX_DIR" -name 'index*')"
EOF

# resetart nginx 
ssh ubuntu@54.87.204.116 << EOF
sudo service nginx reload
EOF
