#!/usr/bin/env bash
# Bash script that displays a list of currently running processes.
# show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy


ps --sort user --forest -Ao user,pid,%cpu,%mem,vsz,rss,tty8,stat,start_time,bsdtime,comm