#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
#Format: The user USERNAME is part of the GROUP_ID gang,
# lives in HOME_DIRECTORY and rides COMMAND/SHELL.
# USER ID's place is protected by the passcode PASSWORD,
# more info about the user here: USER ID INFO

while IFS=: read -r USR PASSWORD USR_ID GRP_ID INFO HOME_DIR CMD_SHELL; do
  echo -n "The user $USR is part of the $GRP_ID gang, lives in $HOME_DIR and rides $CMD_SHELL. "
  echo "$USR_ID's place is protected by the passcode $PASSWORD, more info about the user here: $INFO"

done </etc/passwd
