#!/usr/bin/env bash
#a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

hour=0
minute=0


while (("$hour" <= 12));
do

  if ((minute == 0))
  then echo "Hour: $hour"
  else
    echo "$minute"
  fi

  if ((hour == 12))
  then break;
  fi

  ((minute++))

  if ((minute > 59))
  then
    ((hour++, minute=0))
  fi

done
