#!/usr/bin/env bash
#a Bash script that gives you information about the "school" file

FILE_NAME="school"

if [ -e "$FILE_NAME" ];
then
    echo "$FILE_NAME file exists"

    if [ -s "$FILE_NAME" ];
    then echo "$FILE_NAME file is not empty"
    else echo "$FILE_NAME file is empty"
    fi

    if [ -f "$FILE_NAME" ];
    then echo "$FILE_NAME is a regular file"
    fi

else
    echo "$FILE_NAME file does not exist"
fi